imports:
  - { resource: services_test_doctrine.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  webignition\BasilWorker\PersistenceBundle\Tests\Services\DatabaseSchemaCreator:
    arguments:
      $entityManager: '@Doctrine\ORM\EntityManagerInterface'
      $entityClasses:
        - 'webignition\BasilWorker\PersistenceBundle\Entity\Callback\CallbackEntity'
